# We have a conf and classes directory, set up via BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-appliance-apps"
BBFILE_PATTERN_meta-appliance-apps = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-appliance-apps = "10"

LAYERDEPENDS_meta-appliance-apps = "meta-appliance-os"
LAYERSERIES_COMPAT_meta-appliance-apps = "scarthgap"
