# We have a conf and classes directory, set up via BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-appliance-os"
BBFILE_PATTERN_meta-appliance-os = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-appliance-os = "10"

LAYERDEPENDS_meta-appliance-os = ""
LAYERSERIES_COMPAT_meta-appliance-os = "scarthgap"
