d /data/apps/reticulum 0755 root root -
d /data/apps/reticulum/ratspeak 0750 kiosk kiosk -
d /data/apps/reticulum/rnsd 0755 root root -
d /data/apps/reticulum/rnsd/config 0755 root root -
d /data/apps/reticulum/rnsd/storage 0755 root root -
d /data/apps/reticulum/lxmd 0755 root root -
d /data/apps/reticulum/lxmd/config 0755 root root -
d /data/apps/reticulum/lxmd/storage 0755 root root -
