[Service]
ExecStart=
ExecStart=/usr/sbin/thd --triggers /etc/triggerhappy/triggers.d/ --socket /run/thd.socket --deviceglob /dev/input/event*
User=inputd
Group=inputd
SupplementaryGroups=input pipewire weston
Environment=XDG_RUNTIME_DIR=/run/user/800
Environment=PIPEWIRE_REMOTE=/run/user/800/pipewire-0
Environment=DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/800/bus
