BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-appliance-devtools"
BBFILE_PATTERN_meta-appliance-devtools = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-appliance-devtools = "10"

LAYERDEPENDS_meta-appliance-devtools = "meta-appliance-os"
LAYERSERIES_COMPAT_meta-appliance-devtools = "scarthgap"
