# We have a conf and classes directory, set up via BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-appliance-audio"
BBFILE_PATTERN_meta-appliance-audio = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-appliance-audio = "10"

LAYERDEPENDS_meta-appliance-audio = "meta-appliance-os multimedia-layer"
LAYERSERIES_COMPAT_meta-appliance-audio = "scarthgap"
