# We have a conf and classes directory, set up via BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-kiosk-app-feishin"
BBFILE_PATTERN_meta-kiosk-app-feishin = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-kiosk-app-feishin = "10"

LAYERDEPENDS_meta-kiosk-app-feishin = ""
LAYERSERIES_COMPAT_meta-kiosk-app-feishin = "scarthgap"
